# .github/workflows/deploy_backend_render.yml

name: Build & Deploy Backend to Render - hamburgers-calendar

on:
  push:
    branches:
      - main
    paths:
      - 'packages/express-backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend dependencies
        run: |
          npm install --workspace packages/express-backend

      - name: Run backend tests
        run: |
          npm --workspace packages/express-backend run test --if-present

      - name: Deploy to Render via Deploy Hook
        run: |
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}